import { useCallback, useEffect, useState } from "react";
import { Link, Navigate, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { useDropzone } from "react-dropzone";
import { Aperture, ArrowDown, ArrowLeft, ArrowUp, Bird, Dices, Download, Eye, MoveLeft, MoveRight, RefreshCw, Sparkles, Trash2, Triangle, Upload, UserRound, ZoomIn, ZoomOut } from "lucide-react";

const PREFERENCES_KEY = "shot-explorer:preferences:v1";
const SESSION_KEY = "shot-explorer:session:v1";
const WORKSPACE_DB = "shot-explorer:device-storage:v1";
const WORKSPACE_STORE = "workspace";
const WORKSPACE_ID = "current";
const DEFAULT_SETTINGS = { perspective: "front", panX: 0, panY: 0, zoom: 1 };
const MAX_SAVED_RESULTS = 12;

function readJson(storage, key, fallback = {}) { try { const value = storage?.getItem(key); return value ? JSON.parse(value) : fallback; } catch { return fallback; } }
function writeJson(storage, key, value) { try { storage?.setItem(key, JSON.stringify(value)); } catch { /* Storage can be unavailable in private browsing. */ } }
function readCookie(name) { try { const cookie = document.cookie.split("; ").find((item) => item.startsWith(`${name}=`)); return cookie ? JSON.parse(decodeURIComponent(cookie.slice(name.length + 1))) : {}; } catch { return {}; } }
function writeCookie(name, value) { try { document.cookie = `${name}=${encodeURIComponent(JSON.stringify(value))}; max-age=31536000; path=/; SameSite=Lax`; } catch { /* Cookies can be blocked by the browser. */ } }
function getInitialPreferences() {
  const local = readJson(window.localStorage, PREFERENCES_KEY);
  const session = readJson(window.sessionStorage, SESSION_KEY);
  const cookie = readCookie("shot_explorer_prefs");
  return { mode: "fast", ...cookie, ...local, ...session, settings: { ...DEFAULT_SETTINGS, ...cookie.settings, ...local.settings, ...session.settings } };
}
function openWorkspaceDb() { return new Promise((resolve) => { if (!window.indexedDB) return resolve(null); const request = window.indexedDB.open(WORKSPACE_DB, 1); request.onupgradeneeded = () => request.result.createObjectStore(WORKSPACE_STORE); request.onsuccess = () => resolve(request.result); request.onerror = () => resolve(null); }); }
async function readWorkspace() { const db = await openWorkspaceDb(); if (!db) return null; return new Promise((resolve) => { const request = db.transaction(WORKSPACE_STORE, "readonly").objectStore(WORKSPACE_STORE).get(WORKSPACE_ID); request.onsuccess = () => resolve(request.result || null); request.onerror = () => resolve(null); }); }
async function writeWorkspace(value) { const db = await openWorkspaceDb(); if (!db) return; await new Promise((resolve) => { const request = db.transaction(WORKSPACE_STORE, "readwrite").objectStore(WORKSPACE_STORE).put(value, WORKSPACE_ID); request.onsuccess = request.onerror = () => resolve(); }); }
function readDataUrl(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
function loadImage(url) { return new Promise((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = reject; image.src = url; }); }

function localPreview(image, settings, mode) {
  const canvas = document.createElement("canvas"); canvas.width = 900; canvas.height = 620;
  const context = canvas.getContext("2d"); context.fillStyle = "#eeece3"; context.fillRect(0, 0, canvas.width, canvas.height);
  const imageRatio = image.width / image.height; const canvasRatio = canvas.width / canvas.height; let width = canvas.width; let height = canvas.height;
  if (imageRatio > canvasRatio) height = width / imageRatio; else width = height * imageRatio;
  context.save(); context.translate(canvas.width / 2 + settings.panX * 1.5, canvas.height / 2 + settings.panY * 1.5); const extra = mode === "pro" ? 1.08 : 1; context.scale(settings.zoom * extra, settings.zoom * extra);
  if (settings.perspective === "overhead") context.transform(1, -.12, 0, .78, 0, 0); if (settings.perspective === "side") context.transform(.72, .04, 0, 1, 0, 0); if (settings.perspective === "back") context.scale(-1, 1);
  context.drawImage(image, -width / 2, -height / 2, width, height); context.restore(); return canvas.toDataURL("image/jpeg", .9);
}

function HomePage() {
  return <div className="home-shell"><main className="home-content home-content-top-left"><div className="home-intro"><div className="home-eyebrow">SHOT EXPLORER</div><h1>Create from every angle.</h1><p>Start with one image and find a new perspective.</p></div><section className="home-grid home-grid-top-left" aria-label="Available tools"><motion.article className="home-tool-card" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><div className="home-tool-image"><img src="/assets/shot-explorer-thumbnail.png" alt="Shot Explorer" /></div><div className="home-tool-copy"><div><h2>Shot Explorer</h2><p>See your scene from new angles</p></div><Link className="home-open-link" to="/tools/shot-explorer">Open tool <ArrowRightIcon /></Link></div></motion.article></section></main></div>;
}

function ArrowRightIcon() { return <span aria-hidden="true">→</span>; }

function ShotExplorer() {
  const navigate = useNavigate();
  const initialPreferences = getInitialPreferences();
  const [source, setSource] = useState(null); const [settings, setSettings] = useState(initialPreferences.settings); const [mode, setMode] = useState(initialPreferences.mode); const [results, setResults] = useState([]); const [generating, setGenerating] = useState(false); const [restoring, setRestoring] = useState(true); const [status, setStatus] = useState("Restoring workspace…");
  const setFile = useCallback(async (file) => { if (!file?.type?.startsWith("image/")) return; try { const url = URL.createObjectURL(file); const [image, dataUrl] = await Promise.all([loadImage(url), readDataUrl(file)]); setSource({ fileName: file.name, image, url, dataUrl }); setSettings(DEFAULT_SETTINGS); setResults([]); setStatus("Image ready · saved on this device"); } catch { setStatus("That image could not be opened"); } }, []);
  useEffect(() => { let active = true; readWorkspace().then(async (workspace) => { if (!active) return; if (workspace?.source?.dataUrl) { try { const image = await loadImage(workspace.source.dataUrl); if (active) setSource({ ...workspace.source, image, url: workspace.source.dataUrl }); } catch { if (active) setStatus("Saved image could not be restored"); } } if (active && Array.isArray(workspace?.results)) setResults(workspace.results); if (active) { setStatus(workspace?.source || workspace?.results?.length ? "Workspace restored" : "Ready when you are"); setRestoring(false); } }); return () => { active = false; }; }, []);
  useEffect(() => { if (restoring) return; const preferences = { mode, settings }; writeJson(window.localStorage, PREFERENCES_KEY, preferences); writeJson(window.sessionStorage, SESSION_KEY, preferences); writeCookie("shot_explorer_prefs", preferences); }, [mode, settings, restoring]);
  useEffect(() => { return () => { if (source?.url?.startsWith("blob:")) URL.revokeObjectURL(source.url); }; }, [source]);
  useEffect(() => { if (restoring) return; writeWorkspace({ source: source ? { fileName: source.fileName, dataUrl: source.dataUrl } : null, results: results.slice(0, MAX_SAVED_RESULTS), savedAt: Date.now() }); }, [source, results, restoring]);
  const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop: (files) => setFile(files[0]), accept: { "image/*": [] }, multiple: false });
  const actionLabel = (action, value) => action === "perspective" ? `${value[0].toUpperCase()}${value.slice(1)} angle` : action === "pan" ? `Pan ${value}` : action === "zoom" ? (value === "detail" ? "Extreme detail" : `Zoom ${value}`) : "Surprise angle";
  const generate = async (label, nextSettings = settings) => { if (!source || generating) return; setGenerating(true); setStatus("Generating with Gemini…"); let imageUrl = ""; let usedGemini = false; try { const response = await fetch("/api/generate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ image: source.dataUrl, prompt: `Edit this reference image into a cinematic ${label.toLowerCase()}. Preserve the same subject, identity, environment, colors, and visual style. Change only camera viewpoint and framing. Do not add text, logos, borders, or new objects.` }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(data.error || "Gemini unavailable"); error.status = response.status; throw error; } imageUrl = data.image; usedGemini = true; } catch (error) { imageUrl = localPreview(source.image, nextSettings, mode); const message = error.status === 429 ? `${label} created locally · enable Gemini billing/quota` : error.message.includes("not configured") ? `${label} created locally · add GEMINI_API_KEY for AI` : `${label} created locally · Gemini unavailable`; setStatus(message); } finally { setGenerating(false); } setResults((current) => [{ id: crypto.randomUUID(), label, imageUrl, source: usedGemini ? "Gemini" : "Local" }, ...current].slice(0, MAX_SAVED_RESULTS)); if (!imageUrl) setStatus(`${label} created`); };
  const handleControl = async (action, value) => { if (!source || generating) return; let next = settings; if (action === "surprise") { const perspectives = ["overhead", "side", "back"]; next = { perspective: perspectives[Math.floor(Math.random() * perspectives.length)], panX: Math.round((Math.random() - .5) * 100), panY: Math.round((Math.random() - .5) * 70), zoom: .9 + Math.random() * .8 }; setSettings(next); } else { next = { ...settings }; if (action === "perspective") next.perspective = value; if (action === "pan") { const distance = mode === "pro" ? 54 : 35; next.panX += value === "left" ? -distance : value === "right" ? distance : 0; next.panY += value === "up" ? -distance : value === "down" ? distance : 0; } if (action === "zoom") next.zoom = value === "in" ? Math.min(2.3, settings.zoom + .18) : value === "out" ? Math.max(.72, settings.zoom - .18) : 2.3; setSettings(next); } await generate(actionLabel(action, value || "surprise"), next); };
  const deleteResult = (resultId) => { setResults((current) => current.filter((result) => result.id !== resultId)); setStatus("Angle removed"); };
  const download = (result, index) => { const link = document.createElement("a"); link.href = result.imageUrl; link.download = `shot-explorer-${index + 1}.jpg`; link.click(); };
  const controls = [['Perspective', [['overhead', 'overhead', <Bird size={15} />], ['side', 'side', <Triangle size={15} />], ['back', 'back', <UserRound size={15} />]]], ['Pan', [['left', 'left', <MoveLeft size={15} />], ['right', 'right', <MoveRight size={15} />], ['up', 'up', <ArrowUp size={15} />], ['down', 'down', <ArrowDown size={15} />]]], ['Zoom', [['in', 'zoom in', <ZoomIn size={15} />], ['out', 'zoom out', <ZoomOut size={15} />], ['detail', 'extreme detail', <Eye size={15} />], ['surprise', 'surprise me', <Dices size={15} />]]]];
  return <div className="tool-shell"><main className="tool-content"><header className="tool-topbar"><button className="tool-back" type="button" onClick={() => navigate(-1)} aria-label="Go back"><ArrowLeft size={28} /></button><div className="tool-title"><img className="tool-brand-icon" src="/assets/shot-explorer-thumbnail.png" alt="" /><div><strong>Shot Explorer</strong><small>See your scene from new angles</small></div></div><div className="tool-actions"><button className="done-button" type="button" onClick={() => navigate(-1)}>Done</button></div></header>
    <div className="tool-workspace"><section className="control-panel"><div className="upload-zone"><div className="preview-frame">{source ? <img className="source-image" src={source.url} alt="Selected source" /> : <div className="empty-state"><div className="empty-icon"><Aperture size={46} /></div><p>Select an image to start exploring angles</p></div>}</div><div className={`select-image-button ${isDragActive ? "dragging" : ""}`} {...getRootProps()}><input {...getInputProps()} /><Upload size={18} /> {isDragActive ? "DROP IMAGE" : "SELECT IMAGE"}</div><p className="upload-hint">{source ? `${source.fileName} selected · choose a control to create an angle` : "Drop an image here or choose one from your device"}</p></div>
      <div className="controls">{controls.map(([group, items]) => <div className="control-group" key={group}><div className="group-label">{group}</div><div className="button-row">{items.map(([value, label, icon]) => <button className="control-button" type="button" key={value} disabled={!source || generating} onClick={() => handleControl(group === "Perspective" ? "perspective" : group === "Pan" ? "pan" : value === "surprise" ? "surprise" : "zoom", value)}>{icon}<span>{label}</span></button>)}</div></div>)}</div>
      <div className="bottom-controls"><button className="reset-button" type="button" disabled={!source || generating} onClick={() => { setSettings({ perspective: "front", panX: 0, panY: 0, zoom: 1 }); setStatus("Reset complete"); }}><RefreshCw size={18} /> RESET</button><div className="mode-toggle" role="group" aria-label="Generation mode">{['fast', 'pro'].map((item) => <button className={`mode-button ${mode === item ? "selected" : ""}`} type="button" key={item} onClick={() => setMode(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div></div></section>
      <section className="results-panel"><div className="results-header"><div><div className="eyebrow">GENERATED ANGLES</div><h1>Explore the shot</h1></div><div className="status-pill">{status}</div></div>{results.length ? <div className="results-grid">{results.map((result, index) => <motion.article className="result-card" key={result.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><img src={result.imageUrl} alt={result.label} /><div className="result-meta"><div><div className="result-title">{result.label}</div><div className="result-subtitle">{result.source} · variation {results.length - index}</div></div><div className="result-actions"><button className="download-button" type="button" onClick={() => download(result, index)} aria-label={`Download ${result.label}`}><Download size={17} /></button><button className="delete-button" type="button" onClick={() => deleteResult(result.id)} aria-label={`Delete ${result.label}`}><Trash2 size={17} /></button></div></div></motion.article>)}</div> : <div className="results-empty"><div className="results-empty-icon"><Sparkles size={36} /></div><p>Your explored angles will appear here</p><span>Choose an image, then use the controls on the left.</span></div>}</section></div></main></div>;
}

export default function App() { const location = useLocation(); useEffect(() => { document.title = location.pathname === "/" ? "Shot Explorer — Creative image tools" : "Shot Explorer — Explore your shot from new angles"; }, [location.pathname]); return <Routes><Route path="/" element={<HomePage />} /><Route path="/tools" element={<Navigate to="/" replace />} /><Route path="/tools/shot-explorer" element={<ShotExplorer />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }
